# -*- coding: utf-8 -*-
"""1. Ejercicios Python


Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujn6gSUlFCmXFObNuQyPPDIRpWTRlNbZ

Parametros
Argumentos
Retornos
Funciones
1 crear la funcion
2 llamar funcion
3 retornar
"""

# ******** zona de funciones (se crean las funciones) *******
#           ~~~~ PROGRAMACION MODULAR ~~~~
#las funciones agrupan bloques de codigo
#los comentarios solo los leen los programadores
"""
Estos son comentarios para varios parrafos
se hacen con 3 comillas.
"""

"""
Hacer un programa que genere un saludo
personalizado al usuario
"""
print("hola mundo de python")

#Funcion que toma nombre del usuario
def tomar_nombre():

  print("escribir el nombre del usuario")
  nombre_cliente = input()
  return nombre_cliente

#Funcion que procesa el saludo
def hacer_saludo(dato_nombre):
  mensaje = "Hola usuario: " + str(dato_nombre)
  return mensaje

#Funcion que muestra los resultados
def imprimir_mensaje(dato_mensaje):
  print(dato_mensaje)

# ********* zona de codigo principal *************

dato_nombre = tomar_nombre()

dato_mensaje = hacer_saludo(dato_nombre)
imprimir_mensaje(dato_mensaje)

#EJERCICIO #1

#Calcular el Area de un triangulo con base y altura dadas
print("Hola, Vamos a Mostrar el area del triangulo segun la base y altura que me des.")

#Funcion para tomar la base del triangulo

def tomar_base():
  print("Digite la base del triangulo: ")
  base_triangulo = float(input())
  return base_triangulo

#Funcion para tomar la altura del triangulo

def tomar_altura():
  print("Digite la altura del triangulo: ")
  altura_triangulo = float(input())
  return altura_triangulo

#Funcion para calcular el area

def calcular_area(base_triangulo, altura_triangulo):
  area_calculada = (base_triangulo * altura_triangulo)/2
  return area_calculada

#Funcion para mostrar el area del triangulo

def imprimir_area(dato_area):
  print("El área del triángulo es:", dato_area)

#****************Zona de codigo Principal*************************

base_triangulo = tomar_base()
altura_triangulo = tomar_altura()

# Guardamos el resultado del calculo en una nueva variable
area_final = calcular_area(base_triangulo, altura_triangulo)

# Ahora llamamos a la funcion imprimir_area con el resultado
imprimir_area(area_final)

#EJERCICIO #2

#Determinar el volumen de una esfera con su radio dado

print("Vamos a calcular el volumen de la esfera con el radio")

#Funcion para tomar radio de la esfera
def tomar_radio():
  print("Digite el radio de la esfera: ")
  radio_esfera = float(input())
  return radio_esfera

#Funcion Calcular volumen
def calcular_esfera(radio_esfera):
  volumen_calculado = (4/3)*3.14*(radio_esfera*radio_esfera*radio_esfera)
  return volumen_calculado

#Funcion para mostrar el volumen
def imprimir_volumen(dato_volumen):
  print("El Volumen de la esfera es: ", dato_volumen)

#*********CODIGO PRINCIPAL***************
radio_esfera = tomar_radio()

volumen_final = calcular_esfera(radio_esfera)
imprimir_volumen(volumen_final)

#EJERCICIO #3

#Calcular el area de un rectangulo con la longitud y ancho
print("Vamos a calcular el area del rectangulo con la longitud y elancho")
#Funcion para pedir la logitud
def tomar_longitud():
  print("Digite la longitud: ")
  longitud_rec = float(input())
  return longitud_rec

#Funcion para pedir el ancho
def tomar_ancho():
  print("Digite el ancho: ")
  ancho_rec = float(input())
  return ancho_rec

#Funcion para calcular el area del rec
def calcular_rec(longitud_rec, ancho_rec):
  area_calculada = (longitud_rec*ancho_rec)
  return area_calculada

#Funcio para mostrar el area
def imprimir_area(dato_area):
  print("El Area del Rectangulo es: ", dato_area)

#***********************CODIGO PRINCIPAL*********************
longitud_rec = tomar_longitud()
ancho_rec = tomar_ancho()
area_final = calcular_rec(longitud_rec, ancho_rec)
imprimir_area(area_final)

#EJERCICIO #4
#Determinar el volumen de un cilindro con su radio de la base y altura.

#Funcion para pedir el radio de la base
def tomar_rbase():
  print("Digite el Radio de la base de tu cilindro: ")
  r_base = float(input())
  return r_base

#Funcion para pedir la altura
def tomar_altura():
  print("Digite la altura: ")
  altura = float(input())
  return altura

#Funcion para calcular el volumen del cilindro
def calcular_v(r_base, altura):
  volumen_calculado = (3.14*r_base*r_base*altura)
  return volumen_calculado

#Funcion para mostrar el resultado
def imprimir_v(dato_volumen):
  print("El volumen del cilindro es: ", dato_volumen)

#*********************CODIGO PRINCIPAL************************
r_base = tomar_rbase()
altura = tomar_altura()

volumen_final = calcular_v(r_base, altura)
imprimir_v(volumen_final)

#EJERCICIO #5
#Calcular el area de un circulo con su radio

def tomar_radio():
  print("Digite el radio de su circulo")
  radio = float(input())
  return radio

def calcular_area(radio):
  area_calculada = (3.14*radio*radio)
  return area_calculada

def imprimir_area(dato_area):
  print("El Area del circulo es: ", dato_area)

#*******************CODIGO PRINCIPAL**********************
radio = tomar_radio()
area_final = calcular_area(radio)
imprimir_area(area_final)

#EJERCICIO #6
#Determinar el volumen de un cono con radio de la base y altura

def tomar_r():
  print("Digite el radio: ")
  r = float(input())
  return r

def tomar_a():
  print("Digite la altura: ")
  a = float(input())
  return a

def calcular_v(r, a):
  v_calculado = (1/3)*3.14*(r*r*a)
  return v_calculado

def imprimir_v(dato_v):
  print("El Volumen de tu cono es: ", dato_v)

#****************CODIGO PRINCIPAL******************
r = tomar_r()
a = tomar_a()

v_final = calcular_v(r,a)
imprimir_v(v_final)

#EJERCICIO #7
#Convertir Grados celcius a fahrenheit

def tomar_c():
  print("Digite los celcius: ")
  c = float(input())
  return c

def calcular_f(c):
  f_calculado = c*(9/5) + 32
  return f_calculado

def imprimir_f(dato_f):
  print("Los Celcius ", c , " Convertidos a Fahrenheit da: ", dato_f)

#*************CODIGO PRINCIPAL********************

c= tomar_c()
faren_final= calcular_f(c)
imprimir_f(faren_final)

#EJERCICIO #8
#CONVERTIR DOLARES A EUROS UTILIZANDO UNA TASA DE CAMBIO DADA

def tomar_dl():
  print("Digite los dolares que vas a convertir: ")
  d = float(input())
  return d

def tomar_tasa():
  print("Digite la tasa de cambio: ")
  t = float(input())
  return t

def calcular_cambio(d,t):
  dl_calculado = (d*t)
  return dl_calculado

def imprimir_res(dato_eu):
  print("El cambio de dolares a euros son: ", dato_eu)

#****************CODIGO PRINCIPAL**********************

d = tomar_dl()
t = tomar_tasa()
cambio_final = calcular_cambio(d,t)
imprimir_res(cambio_final)

#EJERCICIO #9
#CALCULAR EL AREA DE UN TRAPECIO CON SUS LONGITUDES DE BASES Y ALTURA

def tomar_b1():
  print("Digite la base mayor: ")
  b1 = float(input())
  return b1

def tomar_b2():
  print("Digite la base menor: ")
  b2 = float(input())
  return b2

def tomar_a():
  print("Digite la altura: ")
  a = float(input())
  return a

def calcular_area(b1,b2,a):
  area_calculada = (b1+b2)*a/2
  return area_calculada

def imprimir_area(dato_area):
  print("El area del Trapecio es: ", dato_area)

#****************CODIGO PRINCIPAL**************

b1 = tomar_b1()
b2 = tomar_b2()
a = tomar_a()
area_final= calcular_area(b1, b2, a)
imprimir_area(area_final)

#EJERCICIO #10
#DETERMINAR EL VOLUMEN DE UN PRISMA RECTANGULAR CON LA LONGITUD, ANCHO Y ALTURA

def tomar_longitud():
  print("Digite la longitud: ")
  l = float(input())
  return l

def tomar_ancho():
  print("DIite el ancho: ")
  anch = float(input())
  return anch

def tomar_altura():
  print("Digite la altura: ")
  a = float(input())
  return a

def calcular_v(l, anch, a):
  volumen_final = (l*anch*a)
  return volumen_final

def imprimir_v(dato_v):
  print("EL volumen del prisma es : " , dato_v)

#********************CODIGO PRINCIPAL************************

l = tomar_longitud()
anch = tomar_ancho()
a = tomar_a()
volumen_final= calcular_v(l, anch, a)
imprimir_v(volumen_final)

#EJERCICIO # 11
#CONVERTIR KILOMETROS A MILLAS

def tomar_kilom():
  print("Digite los kilometros: ")
  k = float(input())
  return k

def calcular_cambio(k):
  cambio_final = (k*0.621371)
  return cambio_final

def imprimir_cambio(dato_final):
  print("Los Kilometros ", k, " Pasados a millas da: ", dato_final)

#***************CODIGO PRINCIPAL**********************
k= tomar_kilom()
cambio_final = calcular_cambio(k)
imprimir_cambio(cambio_final)

#EJERCICIO #12
#CALCULAR EL AREA DE UN CUADRADO CON EL LADO

def tomar_lado():
  print("Digite el lado del cuadrado")
  l = float(input())
  return l

def calcular_area(l):
  area_calculada = (l*l)
  return area_calculada

def imprimir_res(dato_a):
  print("El area del cuadrado es: ", dato_a)

#*************CODIGO PRINCIPAL**********************
l = tomar_lado()
area_calculada = calcular_area(l)
imprimir_res(area_calculada)

#EJERCICIO #13
#DETERMINAR EL VOLUMEN DE UNA PIRAMIDE CON LONGITUD DE LA BASE, ANCHO DE LA BASE
#Y ALTURA ESPECIFICADOS

def tomar_longitud():
  print("Digite la longitud base: ")
  l = float(input())
  return l

def tomar_ancho():
  print("Digite el ancho base: ")
  a = float(input())
  return a

def tomar_altura():
  print("Digite la altura: ")
  h = float(input())
  return h

def calcular_volumen(l,a,h):
  res_vol = (l*a*h)/3
  return res_vol

def imprimir_res(dato_v):
  print("El VOlumen de la Piramide es: ", dato_v)

#*******************CODIGO PRINCIPAL*********************
l = tomar_longitud()
a = tomar_ancho()
h = tomar_altura()

res_vol = calcular_volumen(l,a,h)
imprimir_res(res_vol)

#EJERCICIO #14
#CONVERTIR PULGADAS A CENTIMETROS

def tomar_pulgadas():
  print("Digite las pulgadas para convertirlas a centimetros: ")
  p = float(input())
  return p

def calcular_centimetros(p):
  result_centimetros = (p*2.54)
  return result_centimetros

def imprimir_res(res):
  print("Las pulgadas convertidas a centimetros da: ", res)

#*****************CODIGO PRINCIPAL***********************
p = tomar_pulgadas()
result_centimetros = calcular_centimetros(p)
imprimir_res(result_centimetros)

#EJERCICIO #15
#CALCULAR EL AREA DE UN PARALELOGRAMO CON BASE Y ALTURA

def tomar_base():
  print("Digite la base: ")
  b = float(input())
  return b

def tomar_altura():
  print("DIgite la altura: ")
  h = float(input())
  return h

def calcular_p(b, h):
  res = (b*h)
  return res

def imprimir_res(dato_area):
  print("El area del paralelogramo es: ", dato_area)

#*****************CODIGO PRINCIPAL********************

b = tomar_base()
h = tomar_altura()
res = calcular_p(b, h)

imprimir_res(res)

#EJERCICIO #16
#DETERMINAR VOLUMEN DE UN CUBO CON LA LONGITUD DE UN LADO EN ESPECIFICO

def tomar_lado():
  print("Digite el tamaño del lado: ")
  l = float(input())
  return l

def calcular_volumen(l):
  res = (l*l*l)
  return res

def imprimir_res(dato_volumen):
  print("El volumen del cubo es: " , dato_volumen)


#***********************CODIGO PRINCIPAL********************************

l = tomar_lado()
res = calcular_volumen(l)
imprimir_res(res)

#EJERCICIO #17
#CONVERTIR LIBRAS A KILOGRAMOS

def tomar_libras():
  print("Digite las libras: ")
  l = float(input())
  return l

def calcular_kilogramos(l):
  res = (l*0.4536)
  return res

def imprimir_res(dato_k):
  print("Las libras convertidas a kilogramos dan: ", dato_k)

#****************CODIGO PRUNCIPAL*************************

l = tomar_libras()
res = calcular_kilogramos(l)
imprimir_res(res)

#EJERCICIO #18
#Calcular el área de un hexágono regular con su lado dado

def tomar_lado():
  print("Digite el lado: ")
  l = float(input())
  return l

def calcular_area(l):
  res = (3 * (3**0.5) / 2) * (l**2)
  return res

def imprimir_res(dato_res):
  print("El area del hexagono regular es: ", dato_res)

#***************CODIGO PRINCIPAL********************

l = tomar_lado()
res = calcular_area(l)
imprimir_res(res)

#EJERCICIO #19
#Determinar el volumen de un prisma triangular con la longitud de la
#base, altura y ancho especificados

def tomar_longitud():
  print("Digite la longitud base: ")
  lb = float(input())
  return lb

def tomar_altura():
  print("DIgite la altura:  ")
  h = float(input())
  return h

def tomar_ancho():
  print("Digite el ancho: ")
  a = float(input())
  return a

def calcular_v(lb, h, a):
  res_v = ((lb*h / 2)*a)
  return res_v

def imprimir_res(dato_v):
  print("El volumen del prisma triangular es: ", dato_v)

#**********************CODIGO PRINCIPAL***********************
lb = tomar_longitud()
h = tomar_altura()
a = tomar_ancho()

res_v= calcular_v(lb, h, a)
imprimir_res(res_v)

#EJERCICIO #20
#CONVERTIR LITROS A GALONES

def tomar_litros():
  print("Digite los litros: ")
  l = float(input())
  return l

def calcular_galones(l):
  res = ( l / 3.78541 )
  return res

def imprimir_res(dato_g):
  print("Los litros convertidos a galones da: ", dato_g)

l = tomar_litros()
res = calcular_galones(l)
imprimir_res(res)

#EJERCICIO #21
#PROGRAMA QUE SOLICITE 2 NUMEROS Y MURESTE LA SUMA

def tomar_n1():
  print("Digita el n1: ")
  n1 = int(input())
  return n1

def tomar_n2():
  print("Digite el n2: ")
  n2 = int(input())
  return n2

def calcular(n1, n2):
  res = (n1+n2)
  return res

def imprimir_res(dato_r):
  print("EL resultado es: ", dato_r)

n1 = tomar_n1()
n2 = tomar_n2()

res = calcular(n1,n2)
imprimir_res(res)

#EJERCICIO #22
#Crea un algoritmo que pida al usuario dos números y calcule la resta
#del primero menos el segundo

def tomar_n1():
  print("Digita el n1: ")
  n1 = int(input())
  return n1

def tomar_n2():
  print("Digite el n2: ")
  n2 = int(input())
  return n2

def calcular(n1, n2):
  res = (n1-n2)
  return res

def imprimir_res(dato_r):
  print("EL resultado es: ", dato_r)

n1 = tomar_n1()
n2 = tomar_n2()

res = calcular(n1,n2)
imprimir_res(res)

#EJERCICIO #23
#Desarrolla un programa que requiera dos números y muestre el
#producto de dichos valores.

def tomar_n1():
  print("Digita el n1: ")
  n1 = int(input())
  return n1

def tomar_n2():
  print("Digite el n2: ")
  n2 = int(input())
  return n2

def calcular(n1, n2):
  res = (n1*n2)
  return res

def imprimir_res(dato_r):
  print("EL resultado es: ", dato_r)

n1 = tomar_n1()
n2 = tomar_n2()

res = calcular(n1,n2)
imprimir_res(res)

#EJERCICIO #24
#un algoritmo que pida un número y calcule su cuadrado
#utilizando el operador de multiplicación.
def tomar_n1():
  print("Digita el n1: ")
  n1 = int(input())
  return n1

def calcular(n1):
  res = (n1*n1)
  return res

def imprimir_res(dato_r):
  print("EL resultado es: ", dato_r)

n1 = tomar_n1()

res = calcular(n1)
imprimir_res(res)

#EJERCICIO #25
#programa que solicite dos números y calcule la división del
#primero entre el segundo

def tomar_n1():
  print("Digita el n1: ")
  n1 = int(input())
  return n1

def tomar_n2():
  print("Digite el n2: ")
  n2 = int(input())
  return n2

def calcular(n1, n2):
  res = (n1/n2)
  return res

def imprimir_res(dato_r):
  print("EL resultado es: ", dato_r)

n1 = tomar_n1()
n2 = tomar_n2()

res = calcular(n1,n2)
imprimir_res(res)

#EJERCICIO #26
#algoritmo que determine el residuo de la división entre dos
#números ingresados por el usuario

def tomar_n1():
  print("Digita el n1: ")
  n1 = int(input())
  return n1

def tomar_n2():
  print("Digite el n2: ")
  n2 = int(input())
  return n2

def calcular(n1, n2):
  res = (n1%n2)
  return res

def imprimir_res(dato_r):
  print("EL resultado es: ", dato_r)

n1 = tomar_n1()
n2 = tomar_n2()

res = calcular(n1,n2)
imprimir_res(res)

#EJERCICIO #27
#programa que pida un número y calcule su raíz cuadrada
#utilizando operadores aritméticos

def tomar_n1():
  print("Digita el n1: ")
  n1 = int(input())
  return n1

def calcular(n1):
  res = (n1**0.5)
  return res

def imprimir_res(dato_r):
  print("EL resultado es: ", dato_r)

n1 = tomar_n1()

res = calcular(n1)
imprimir_res(res)

#EJERCICIO #28
#algoritmo que solicite la base y la altura de un triángulo y
#calcule su área
def tomar_base():
  print("Digite la base del triangulo: ")
  base_triangulo = float(input())
  return base_triangulo

def tomar_altura():
  print("Digite la altura del triangulo: ")
  altura_triangulo = float(input())
  return altura_triangulo

def calcular_area(base_triangulo, altura_triangulo):
  area_calculada = (base_triangulo * altura_triangulo)/2
  return area_calculada

def imprimir_area(dato_area):
  print("El área del triángulo es:", dato_area)

base_triangulo = tomar_base()
altura_triangulo = tomar_altura()
area_final = calcular_area(base_triangulo, altura_triangulo)

imprimir_area(area_final)

#EJERCICIO #29
#programa que pida un número y determine si es par o impar
#usando el operador de módulo (%)

def tomar_n1():
  print("Digite el numero: ")
  n = int(input())
  return n

def calcular_res(n):
  res= (n % 2)
  return res

def imprimir_res(dato_r):
  if n % 2 == 0:
    print("El numero es Par")
  else:
    print("El numero es Impar")

n = tomar_n1()
res= calcular_res(n)
imprimir_res(res)

#EJERCICIO #30
#algoritmo que solicite el radio de un círculo y calcule su
#circunferencia

def tomar_radio():
  print("Digite el radio: ")
  r = float(input())
  return r

def calcular(r):
  res= (2 * 3.14 * r)
  return res

def imprimir(dato_res):
  print("La circunferencia es: ", dato_res)

r = tomar_radio()
res = calcular(r)
imprimir(res)

#EJERCICIO #31
#programa que pida un número de horas y lo convierta a
#minutos utilizando operadores aritméticos.

def tomar_horas():
  print("DIgite las horas: ")
  h = float(input())
  return h

def calcular(h):
  res = (h *60)
  return res

def imprimir(dato_res):
  print("Los horas convertidas a minutos son: ", dato_res)

r = tomar_horas()
res = calcular(r)
imprimir(res)

#EJERCICIO #32
#Calcular el area de un rectangulo con la longitud y ancho
print("Vamos a calcular el area del rectangulo con la longitud y elancho")

def tomar_longitud():
  print("Digite la longitud: ")
  longitud_rec = float(input())
  return longitud_rec

def tomar_ancho():
  print("Digite el ancho: ")
  ancho_rec = float(input())
  return ancho_rec

def calcular_rec(longitud_rec, ancho_rec):
  area_calculada = (longitud_rec*ancho_rec)
  return area_calculada

def imprimir_area(dato_area):
  print("El Area del Rectangulo es: ", dato_area)

longitud_rec = tomar_longitud()
ancho_rec = tomar_ancho()
area_final = calcular_rec(longitud_rec, ancho_rec)
imprimir_area(area_final)

#EJERCICIO #33
# algoritmo que solicite una distancia en kilómetros y la convierta
#a millas

def tomar_kilom():
  print("Digite los kilometros: ")
  k = float(input())
  return k

def calcular_cambio(k):
  cambio_final = (k*0.621371)
  return cambio_final

def imprimir_cambio(dato_final):
  print("Los Kilometros ", k, " Pasados a millas da: ", dato_final)

#***************CODIGO PRINCIPAL**********************
k= tomar_kilom()
cambio_final = calcular_cambio(k)
imprimir_cambio(cambio_final)

#EJERCICIO #34
#programa que pida el precio de un artículo y calcule el 10%
#de descuento

def tomar_precio():
  print("Digite el precio del articulo: ")
  p = float(input())
  return p

def calcular(p):
  res = (p*0.10)
  res =(p-10)
  return res

def imprimir(dato):
  print("El Precio con el 10% de descuento queda en: ", dato)

p = tomar_precio()
res = calcular(p)
imprimir(res)

#EJERCICIO #35
#algoritmo que solicite la cantidad de dinero en una cuenta y
#calcule el 5% de interés.

def dinero_cuenta():
  print("DIgite la cantidad de dinero que tienes en la cuenta: ")
  d = float(input())
  return d

def calcular(d):
  res = (d * 0.05)
  return res

def imprimir(dato):
  print("Tu dinero en la cuenta con el 5% de interes da: ", dato)

d = dinero_cuenta()
res = calcular(d)
imprimir(res)

#EJERCICIO #36
#programa que pida dos números enteros y muestre el
#cociente de la división entera

def numero_1():
  print("Digite el numero 1: ")
  n1 = int(input())
  return n1

def numero_2():
  print("Digite el numero 2: ")
  n2 = int(input())
  return n2

def calcular(n1,n2):
  res = (n1 // n2)
  return res

def imprimir(dato):
  print("El Cociente es: ", dato)

n1 = numero_1()
n2 = numero_2()
res = calcular(n1,n2)
imprimir(res)

#EJERCICIO #37
#algoritmo que determine si un número es múltiplo de otro
#ingresados por el usuario

def numero_1():
  print("Digite el numero 1: ")
  n1 = int(input())
  return n1

def numero_2():
  print("Digite el numero 2: ")
  n2 = int(input())
  return n2

def calcular(n1,n2):
  res = (n1 % n2)
  return res

def imprimir(dato):
  if (n1 % n2 == 0):
    print("El numero 1:", n1, " Si es multiplo de: ", n2)
  else:
    print("El numero 1:", n1, " NO es multiplo de: ", n2)

n1 = numero_1()
n2 = numero_2()
res = calcular(n1,n2)
imprimir(res)

#EJERCICIO #38
#programa que pida dos números y muestre el mayor de
#Los dos utilizando operadores aritméticos

def numero_1():
  print("Digite el numero 1: ")
  n1 = int(input())
  return n1

def numero_2():
  print("Digite el numero 2: ")
  n2 = int(input())
  return n2

def calcular(n1, n2):
  res = (n1 > n2)
  return(res)

def imprimir(dato):
  if (n1 > n2):
    print("El numero 1:", n1 ,"es MAYOR")
  else:
    print("EL numero 2:", n2 ,"es MAYOR")

n1 = numero_1()
n2 = numero_2()
res = calcular(n1, n2)
imprimir(res)

#EJERCICIO #39
#lgoritmo que solicite dos números y calcule el promedio de ambos

def numero_1():
  print("Digite el numero 1: ")
  n1 = int(input())
  return n1

def numero_2():
  print("Digite el numero 2: ")
  n2 = int(input())
  return n2

def calcular(n1, n2):
  res = (n1 + n2)/2
  return(res)

def imprimir(dato):
  print("El promedio de ambos numero es: ", dato)

n1 = numero_1()
n2 = numero_2()
res = calcular(n1, n2)
imprimir(res)
