# -*- coding: utf-8 -*-
"""2. PROGRAMACION POO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FeR9tAv9hVcIWaaei3kWko2DvZzzmC2Z
"""

#EJERCICIO #1
#CREAR UNA CLASE

#**********ZONA DE CLASES**********************

class Triangulo:
  def __init__(self):
    self.altura = " "
    self.base = " "
    self.resultado = " "

  def tomar_base(self):
    base = int(input("Digite la base: "))
    return base

  def tomar_altura(self):
    altura = int(input("Digite la altura: "))
    return altura

#Se settear los atributos(set)

  def asignar_datos(self, altura, base):
    self.altura = altura
    self.base = base



  def calcular_area(self):
    self.resultado = (self.base * self.altura)/2

  def imprimir(self):
    info ="El resultado es: " + str(self.resultado)
    return info


#******************ZONA DE CODIGO PRINCIPAL********************

#LLAMAR O CREAR EL OBJETO

obj_triangulo = Triangulo()
dato_altura = obj_triangulo.tomar_altura()
dato_base = obj_triangulo.tomar_base()
obj_triangulo.asignar_datos(dato_altura, dato_base)
obj_triangulo.calcular_area()
print(obj_triangulo.imprimir())

#EJERCICIO #2
#DETERMINAR EL VOLUMEN DE UNA ESFERA CON SU RADIO

#************************ZONA DE CLASES******************************

#CREAR CLASE
class Esfera:
  def __init__(self):
    self.radio = " "
    self.res = " "

  def tomar_radio(self):
    radio = int(input("DIgite el radio: "))
    return radio

# SETTEAR LOS ATRIBUTOS (set)

  def asignar_datos(self, radio):
    self.radio = radio

  def calcular(self):
    self.res = (4/3)*3.14*(self.radio*self.radio*self.radio)

  def imprimir(self):
    info = "EL resultado es: " + str(self.res)
    return info

  # ********************ZONA DE CODIGO PRINCIPAL****************************
  #CREAR OBJETO

obj_esfera =Esfera()
radio = obj_esfera.tomar_radio()
obj_esfera.asignar_datos(radio)
obj_esfera.calcular()
print(obj_esfera.imprimir())

#EJERCICIO #3
#Calcular el área de un rectángulo con longitud y ancho dados

#*************ZONA DE CREAR CLASES********************

#CREAR CLASE

class Rectangulo:
  def __init__(self):
    self.longitud= " "
    self.ancho= " "
    self.res = " "

  def tomar_longitud(self):
    longitud = float(input("Digite la longitud del rectangulo: "))
    return longitud

  def tomar_ancho(self):
    ancho = float(input("Digite el ancho del rectangulo: "))
    return ancho

  #SETTEAR LOS ATRIBUTOS (SET)

  def asignar_datos(self, longitud, ancho):
    self.longitud = longitud
    self.ancho = ancho

  def calcular_area(self):
    self.res = (self.longitud*self.ancho)

  def imprimir(self):
    info = "El resultado es: " + str(self.res)
    return info

  #**************ZONA DE CODIGO PRINCIPAL******************

  #LLAMR O CREAR EL OBJETO

obj_rectangulo = Rectangulo()
dato_longitud = obj_rectangulo.tomar_longitud()
dato_ancho = obj_rectangulo.tomar_ancho()

obj_rectangulo.asignar_datos(dato_longitud, dato_ancho)
obj_rectangulo.calcular_area()
print(obj_rectangulo.imprimir())

#EJERCICIO #4
#Determinar el volumen de un cilindro con su radio de la base y altura

#******************ZONA DE CLASES*************************
#CREAMOS LA CLASE

class Cilindro:
  def __init__(self):
    self.radiob = " "
    self.altura = " "
    self.res = " "

  def tomar_radiob(self):
    radiob = float(input("Digite la radio de la base: "))
    return radiob

  def tomar_altura(self):
    altura = float(input("Digite la altura:"))
    return altura

  #SETTEAR LOS ATRIBUTOS (set)

  def asignar_datos(self, radiob, altura):
    self.radiob = radiob
    self.altura = altura

  def calcular_volumen(self):
    self.res = (3.14*self.radiob*self.radiob*self.altura)

  def imprimir(self):
      info = "El Volumen del cilindro es: " + str(self.res)
      return info

  #**************CODIGO PRINCIPAL***********************

  #LLAMAR O CREAR EL OBJETO

obj_cilindro = Cilindro()
dato_radiob = obj_cilindro.tomar_radiob()
dato_altura = obj_cilindro.tomar_altura()
obj_cilindro.asignar_datos(dato_radiob, dato_altura)
obj_cilindro.calcular_volumen()
print(obj_cilindro.imprimir())

#EJERCICIO #5
#Calcular el área de un círculo con su radio dado

#******************ZONA DE CLASES**********************

#CREAMOS LA CLASE

class Circulo:
  def __init__(self):
    self.radio = " "
    self.res = " "

  def tomar_radio(self):
    radio = float(input("DIgite el radio del circulo: "))
    return radio

#****************SETTEAR DATOS  (SET)***********************
  def asignar_datos(self, radio):
    self.radio = radio

  def calcular(self):
    self.res = (3.14159 * self.radio ** 2)

  def imprimir(self):
    info = "El area del circulo es: " + str(self.res)
    return info

#**************ZONA DE CODIGO PRINCIPAL*****************
#LLAMAR O CREAR EL OBJETO

obj_circulo = Circulo()
dato_radio = obj_circulo.tomar_radio()
obj_circulo.asignar_datos(dato_radio)
obj_circulo.calcular()
print(obj_circulo.imprimir())

#EJERCICIO #6
#Determinar el volumen de un cono con radio de la base y altura

class Cono:
  def __init__(self):
    self.radiob = " "
    self.altura = " "

  def tomar_radiob(self):
    radiob = float(input("Digite el radio base del cono: "))
    return radiob

  def tomar_altura(self):
    altura = float(input("Digite la altura del cono: "))
    return altura

  #SETTEARR

  def asignar_datos(self, radiob, altura):
    self.radiob = radiob
    self.altura = altura

  def calcular(self):
    self.res = ((1/3) * 3.14159 * self.radiob**2 * self.altura)

  def imprimir(self):
    info = "El volumen del cono es: " + str(self.res)
    return info

  #**************CODIGO PRINCIPAL*******************
  #CREAR OBJ

obj_cono = Cono()
dato_radiob = obj_cono.tomar_radiob()
dato_altura = obj_cono.tomar_altura()

obj_cono.asignar_datos(dato_radiob, dato_altura)
obj_cono.calcular()
print(obj_cono.imprimir())

#EJERCICIO #7

##Convertir Grados celcius a fahrenheit

#CREAMOS CLASE

class Fahrenheit:
  def __init__(self):
    self.celcius = " "
    self.res = " "

  def tomar_celcius(self):
    celcius = float(input("DIgite los grados celcius para convertirlos: "))
    return celcius

#SETTEAR

  def asignar_datos(self, celcius):
    self.celcius = celcius

  def calcular(self):
    self.res = (self.celcius * 1.8) + 32

  def imprimir(self):
    info = "Los grados convertidos dan: " + str(self.res)
    return info

  #**********************CODIGO PRINCIPAL********************

obj_fahrenheit = Fahrenheit()
dato_celcius = obj_fahrenheit.tomar_celcius()
obj_fahrenheit.asignar_datos(dato_celcius)
obj_fahrenheit.calcular()
print(obj_fahrenheit.imprimir())

#EJERCICIO #8
#CONVERTIR DOLARES A EUROS UTILIZANDO UNA TASA DE CAMBIO DADA

#CREAR CLASE

class Euros:
  def __init__(self):
    self.dolares = " "
    self.tasa = " "
    self.res = " "

  def tomar_dolares(self):
    dolares = float(input("Digite los dolares a convertir: "))
    return dolares

  def tomar_tasa(self):
    tasa = float(input("DIgite la tasas de cambio: "))
    return tasa

#SETTEAR

  def asignar_datos(self, dolares, tasa):
    self.dolares = dolares
    self.tasa = tasa

  def calcular(self):
    self.res = (self.dolares*self.tasa)

  def imprimir(self):
    info = "Los dolares convertids a Euros son: " + str(self.res)
    return info

#********CODIGO PRICIPAL*****************
#CREAR OBJ

obj_euros = Euros()
dato_dolares = obj_euros.tomar_dolares()
dato_tasa = obj_euros.tomar_tasa()
obj_euros.asignar_datos(dato_dolares, dato_tasa)
obj_euros.calcular()
print(obj_euros.imprimir())

#EJERCICIO #9
#CALCULAR EL AREA DE UN TRAPECIO CON SUS LONGITUDES DE BASES Y ALTURA

#CREAMOS CLASE

class Trapecio:
  def __init__(self):
    self.baseM = " "
    self.basem = " "
    self.altura = " "
    self.res = " "

  def tomar_base1(self):
    baseM = float(input("Digite la base mayor del trapecio: "))
    return baseM

  def tomar_base2(self):
    basem = float(input("Digite la base menor del trapecio: "))
    return basem

  def tomar_altura(self):
    altura = float(input("DIgite la altura del trapecio: "))
    return altura

  #SETTEAR

  def asignar_datos(self, baseM, basem, altura):
    self.baseM = baseM
    self.basem = basem
    self.altura = altura

  def calcular(self):
    self.res = (self.baseM + self.basem)*self.altura /2

  def imprimir(self):
    info = "EL area del trapecio es: " + str(self.res)
    return info

  #CODIGO PRINCIPALLLLLLLL
  #CREAMOS OBJ

obj_trapecio = Trapecio()
dato_baseM = obj_trapecio.tomar_base1()
dato_basem = obj_trapecio.tomar_base2()
dato_altura = obj_trapecio.tomar_altura()
obj_trapecio.asignar_datos(dato_baseM, dato_basem, dato_altura)
obj_trapecio.calcular()
print(obj_trapecio.imprimir())

#EJERCICIO #10
#DETERMINAR EL VOLUMEN DE UN PRISMA RECTANGULAR CON LA LONGITUD, ANCHO Y ALTURA

class Prisma:
  def __init__(self):
    self.l = " "
    self.a = " "
    self.h = " "
    self.res = " "

  def tomar_l(self):
    l = float(input("DIGITE la longitud: "))
    return l

  def tomar_a(self):
    a = float(input("Digite el ancho: "))
    return a

  def tomar_h(self):
    h = float(input("Digite la altura: "))
    return h

#SETTEAR

  def asignar_datos(self, l, a, h):
    self.l = l
    self.a = a
    self.h = h

  def calcular(self):
    self.res = (self.l * self.a * self.h)

  def imprimir(self):
    info = "el volumen es: " + str(self.res)
    return info

#CODIGO PRINCIPAL
#CREAR OBJ

obj_prisma = Prisma()
dato_l = obj_prisma.tomar_l()
dato_a = obj_prisma.tomar_a()
dato_h = obj_prisma.tomar_h()
obj_prisma.asignar_datos(dato_l, dato_a, dato_h)
obj_prisma.calcular()
print(obj_prisma.imprimir())

#EJERCICIO #11
#CONVERTIR KILOMETROS A MILLAS

class Millas:
  def __init__(self):
    self.k = " "
    self.res = " "

  def tomar_k(self):
    k = float(input("DIgite los kilometros: "))
    return k

  #SETTEAR

  def asignar_datos(self, k):
    self.k = k

  def calcular(self):
    self.res = (self.k*0.621371)

  def imprimir(self):
    info = "Los kilometros a millas dan: " + str(self.res)
    return info
  #CODIGO PRONCIPAL
  #CREAR OBJ

obj_millas = Millas()
dato_k = obj_millas.tomar_k()
obj_millas.asignar_datos(dato_k)
obj_millas.calcular()
print(obj_millas.imprimir())

#EJERCICIO #12
#CALCULAR EL AREA DE UN CUADRADO CON EL LADO

class Cuadrado:
  def __init__(self):
    self.l = " "
    self.res = " "

  def tomar_l(self):
    l = float(input("Digite el lado: "))
    return l

  #SETTEAR

  def asignar_datos(self, l):
    self.l = l

  def calcular(self):
    self.res = (self.l * self.l)

  def imprimir(self):
    info = "El area del cuadrado es: " + str(self.res)
    return info

  #CODIGO PRINCIPAL
  #CREACION DE OBJ

obj_cuadrado = Cuadrado()
dato_l = obj_cuadrado.tomar_l()
obj_cuadrado.asignar_datos(dato_l)
obj_cuadrado.calcular()
print(obj_cuadrado.imprimir())

#EJERCICIO #13
#DETERMINAR EL VOLUMEN DE UNA PIRAMIDE CON LONGITUD DE LA BASE, ANCHO DE LA BASE
#Y ALTURA ESPECIFICADOS

class Piramide:
  def __init__(self):
    self.l = " "
    self.a = " "
    self.h = " "
    self.res = " "

  def tomar_l(self):
    l = float(input("Digite la longitu: "))
    return l

  def tomar_a(self):
    a = float(input("Digite el ancho: "))
    return a

  def tomar_h(self):
    h = float(input("Digite la alturA:"))
    return h

  #SETTEAR

  def asignar_datos(self, l, a, h):
    self.l = l
    self.a = a
    self.h = h

  def calcular(self):
    self.res = (self.l * self.a * self.h)/3

  def imprimir(self):
    info = "El volumen es: " + str(self.res)
    return info

  #CODIGO PRINCIPAL
  #CREAR OBJ

obj_piramide = Piramide()
dato_l = obj_piramide.tomar_l()
dato_a = obj_piramide.tomar_a()
dato_h = obj_piramide.tomar_h()
obj_piramide.asignar_datos(dato_l, dato_a, dato_h)
obj_piramide.calcular()
print(obj_piramide.imprimir())

#EJERCCIIO #14
#CONVERTIR PULGADAS A CENTIMETROS

class Centimetros:
  def __init__(self):
    self.p = " "
    self.res = " "

  def tomar_p(self):
    p = float(input("DIgite las pulgadas: "))
    return p

  #SETTEAR

  def asignar_datos(self, p):
    self.p = p

  def calcular(self):
    self.res = (self.p *2.54)

  def imprimir(self):
    info = "Las pulgadas a centimetros dan: " + str(self.res)
    return info
  #CODIGO PRONCIPAL
  #CREAR OBJ

obj_centimetros = Centimetros()
dato_p = obj_centimetros.tomar_p()
obj_centimetros.asignar_datos(dato_p)
obj_centimetros.calcular()
print(obj_centimetros.imprimir())

#EJERCICIO #15
#CALCULAR EL AREA DE UN PARALELOGRAMO CON BASE Y ALTURA

class Paralelogramo:
  def __init__(self):
    self.altura = " "
    self.base = " "
    self.resultado = " "

  def tomar_base(self):
    base = float(input("Digite la base: "))
    return base

  def tomar_altura(self):
    altura = float(input("Digite la altura: "))
    return altura

#Se settear los atributos(set)

  def asignar_datos(self, altura, base):
    self.altura = altura
    self.base = base



  def calcular_area(self):
    self.resultado = (self.base * self.altura)

  def imprimir(self):
    info ="El resultado es: " + str(self.resultado)
    return info


#******************ZONA DE CODIGO PRINCIPAL********************

#LLAMAR O CREAR EL OBJETO

obj_paralelogramo = Paralelogramo()
dato_altura = obj_paralelogramo.tomar_altura()
dato_base = obj_paralelogramo.tomar_base()
obj_paralelogramo.asignar_datos(dato_altura, dato_base)
obj_paralelogramo.calcular_area()
print(obj_paralelogramo.imprimir())

#EJERCICIO #16
#DETERMINAR VOLUMEN DE UN CUBO CON LA LONGITUD DE UN LADO EN ESPECIFICO
class Cubo:
  def __init__(self):
    self.l = " "
    self.res = " "

  def tomar_l(self):
    l = float(input("Digite el lado: "))
    return l

  #SETTEAR

  def asignar_datos(self, l):
    self.l = l

  def calcular(self):
    self.res = (self.l * self.l * self.l)

  def imprimir(self):
    info = "El area del cuadrado es: " + str(self.res)
    return info

  #CODIGO PRINCIPAL
  #CREACION DE OBJ

obj_cubo = Cubo()
dato_l = obj_cubo.tomar_l()
obj_cubo.asignar_datos(dato_l)
obj_cubo.calcular()
print(obj_cubo.imprimir())

#EJERCICIO #17
#CONVERTIR LIBRAS A KILOGRAMOS

class Kilogramos:
  def __init__(self):
    self.l = " "
    self.res = " "

  def tomar_l(self):
    l = float(input("DIgite las libras: "))
    return l

  #SETTEAR

  def asignar_datos(self, l):
    self.l = l

  def calcular(self):
    self.res = (self.l *0.4536)

  def imprimir(self):
    info = "Las libras a kilogramos dan: " + str(self.res)
    return info

  #CODIGO PRONCIPAL
  #CREAR OBJ

obj_kilogramos = Kilogramos()
dato_l = obj_kilogramos.tomar_l()
obj_kilogramos.asignar_datos(dato_l)
obj_kilogramos.calcular()
print(obj_kilogramos.imprimir())

#EJERCICIO #18
#Calcular el área de un hexágono regular con su lado dado

class Hexagono:
  def __init__(self):
    self.l = " "
    self.res = " "

  def tomar_l(self):
    l = float(input("Digite el lado: "))
    return l

  #SETTEAR

  def asignar_datos(self, l):
    self.l = l

  def calcular(self):
    self.res = (3 * (3**0.5) / 2) * (self.l**2)

  def imprimir(self):
    info = "El area del hexagono es: " + str(self.res)
    return info

  #CODIGO PRINCIPAL
  #CREACION DE OBJ

obj_hexagono = Hexagono()
dato_l = obj_hexagono.tomar_l()
obj_hexagono.asignar_datos(dato_l)
obj_hexagono.calcular()
print(obj_hexagono.imprimir())

#EJERCICIO #19
#Determinar el volumen de un prisma triangular con la longitud de la
#base, altura y ancho especificados

class Prisma:
  def __init__(self):
    self.l = " "
    self.a = " "
    self.h = " "
    self.res = " "

  def tomar_l(self):
    l = float(input("DIGITE la longitud: "))
    return l

  def tomar_a(self):
    a = float(input("Digite el ancho: "))
    return a

  def tomar_h(self):
    h = float(input("Digite la altura: "))
    return h

#SETTEAR

  def asignar_datos(self, l, a, h):
    self.l = l
    self.a = a
    self.h = h

  def calcular(self):
    self.res = ((self.l* self.h / 2)* self.a)

  def imprimir(self):
    info = "el volumen es: " + str(self.res)
    return info

#CODIGO PRINCIPAL
#CREAR OBJ

obj_prisma = Prisma()
dato_l = obj_prisma.tomar_l()
dato_a = obj_prisma.tomar_a()
dato_h = obj_prisma.tomar_h()
obj_prisma.asignar_datos(dato_l, dato_a, dato_h)
obj_prisma.calcular()
print(obj_prisma.imprimir())

#EJERCICIO #20
#CONVERTIR LITROS A GALONES
class Galones:
  def __init__(self):
    self.l = " "
    self.res = " "

  def tomar_l(self):
    l = float(input("DIgite las litros: "))
    return l

  #SETTEAR

  def asignar_datos(self, l):
    self.l = l

  def calcular(self):
    self.res = (self.l / 3.78541)

  def imprimir(self):
    info = "Las libras a kilogramos dan: " + str(self.res)
    return info

  #CODIGO PRONCIPAL
  #CREAR OBJ

obj_galones = Galones()
dato_l = obj_galones.tomar_l()
obj_galones.asignar_datos(dato_l)
obj_galones.calcular()
print(obj_galones.imprimir())

#EJERCICIO #21
#PROGRAMA QUE SOLICITE 2 NUMEROS Y MURESTE LA SUMA

#CREAMOS CLASE

class Suma:
  def __init__(self):
    self.n1 = " "
    self.n2 = " "
    self.res = " "

  def tomar_n1(self):
    n1 = int(input("Digite el numero 1: "))
    return n1

  def tomar_n2(self):
    n2 = int(input("Digite el numero 2: "))
    return n2

  #SETEAR

  def asignar_datos(self, n1, n2):
    self.n1 = n1
    self.n2 = n2

  def calcular(self):
    self.res = (self.n1+ self.n2)

  def imprimir(self):
    info = "La suma da: " + str(self.res)
    return info

  #CODIGO PRINCIPAL
  #CREACION DE OBJETOS

obj_suma = Suma()
dato_n1 = obj_suma.tomar_n1()
dato_n2 = obj_suma.tomar_n2()
obj_suma.asignar_datos(dato_n1, dato_n2)
obj_suma.calcular()
print(obj_suma.imprimir())

#EJERCICIO #22
#Crea un algoritmo que pida al usuario dos números y calcule la resta
#del primero menos el segundo

class Resta:
  def __init__(self):
    self.n1 = " "
    self.n2 = " "
    self.res = " "

  def tomar_n1(self):
    n1 = int(input("Digite el numero 1: "))
    return n1

  def tomar_n2(self):
    n2 = int(input("Digite el numero 2: "))
    return n2

  #SETEAR

  def asignar_datos(self, n1, n2):
    self.n1 = n1
    self.n2 = n2

  def calcular(self):
    self.res = (self.n1 - self.n2)

  def imprimir(self):
    info = "La Resta da: " + str(self.res)
    return info

  #CODIGO PRINCIPAL
  #CREACION DE OBJETOS

obj_resta = Resta()
dato_n1 = obj_resta.tomar_n1()
dato_n2 = obj_resta.tomar_n2()
obj_resta.asignar_datos(dato_n1, dato_n2)
obj_resta.calcular()
print(obj_resta.imprimir())

#EJERCICIO #23
#Desarrolla un programa que requiera dos números y muestre el
#producto de dichos valores

class Multi:
  def __init__(self):
    self.n1 = " "
    self.n2 = " "
    self.res = " "

  def tomar_n1(self):
    n1 = int(input("Digite el numero 1: "))
    return n1

  def tomar_n2(self):
    n2 = int(input("Digite el numero 2: "))
    return n2

  #SETEAR

  def asignar_datos(self, n1, n2):
    self.n1 = n1
    self.n2 = n2

  def calcular(self):
    self.res = (self.n1 * self.n2)

  def imprimir(self):
    info = "La Multiplicacion da: " + str(self.res)
    return info

  #CODIGO PRINCIPAL
  #CREACION DE OBJETOS

obj_multi = Multi()
dato_n1 = obj_multi.tomar_n1()
dato_n2 = obj_multi.tomar_n2()
obj_multi.asignar_datos(dato_n1, dato_n2)
obj_multi.calcular()
print(obj_multi.imprimir())

#EJERCICIO #24
#un algoritmo que pida un número y calcule su cuadrado
#utilizando el operador de multiplicación

class Cuadrado:
  def __init__(self):
    self.l = " "
    self.res = " "

  def tomar_l(self):
    l = float(input("DIgite el numero del lado: "))
    return l

  #SETTEAR

  def asignar_datos(self, l):
    self.l = l

  def calcular(self):
    self.res = (self.l * self.l)

  def imprimir(self):
    info = "El cuadrado es: " + str(self.res)
    return info

  #CODIGO PRONCIPAL
  #CREAR OBJ

obj_cuadrado = Cuadrado()
dato_l = obj_cuadrado.tomar_l()
obj_cuadrado.asignar_datos(dato_l)
obj_cuadrado.calcular()
print(obj_cuadrado.imprimir())

#EJERCICIO #25
#programa que solicite dos números y calcule la división del
#primero entre el segundo


class Div:
  def __init__(self):
    self.n1 = " "
    self.n2 = " "
    self.res = " "

  def tomar_n1(self):
    n1 = int(input("Digite el numero 1: "))
    return n1

  def tomar_n2(self):
    n2 = int(input("Digite el numero 2: "))
    return n2

  #SETEAR

  def asignar_datos(self, n1, n2):
    self.n1 = n1
    self.n2 = n2

  def calcular(self):
    self.res = (self.n1 / self.n2)

  def imprimir(self):
    info = "La Divicion da: " + str(self.res)
    return info

  #CODIGO PRINCIPAL
  #CREACION DE OBJETOS

obj_div = Div()
dato_n1 = obj_div.tomar_n1()
dato_n2 = obj_div.tomar_n2()
obj_div.asignar_datos(dato_n1, dato_n2)
obj_div.calcular()
print(obj_div.imprimir())

#EJERCICIO #26
#algoritmo que determine el residuo de la división entre dos
#números ingresados por el usuario

class Res:
  def __init__(self):
    self.n1 = " "
    self.n2 = " "
    self.res = " "

  def tomar_n1(self):
    n1 = int(input("Digite el numero 1: "))
    return n1

  def tomar_n2(self):
    n2 = int(input("Digite el numero 2: "))
    return n2

  #SETEAR

  def asignar_datos(self, n1, n2):
    self.n1 = n1
    self.n2 = n2

  def calcular(self):
    self.res = (self.n1 % self.n2)

  def imprimir(self):
    info = "El residuo es: " + str(self.res)
    return info

  #CODIGO PRINCIPAL
  #CREACION DE OBJETOS

obj_res = Res()
dato_n1 = obj_res.tomar_n1()
dato_n2 = obj_res.tomar_n2()
obj_res.asignar_datos(dato_n1, dato_n2)
obj_res.calcular()
print(obj_res.imprimir())

#EJERCICIO #27
#programa que pida un número y calcule su raíz cuadrada
#utilizando operadores aritméticos

class Raiz:
  def __init__(self):
    self.l = " "
    self.res = " "

  def tomar_l(self):
    l = float(input("DIgite el numero: "))
    return l

  #SETTEAR

  def asignar_datos(self, l):
    self.l = l

  def calcular(self):
    self.res = (self.l ** 0.5)

  def imprimir(self):
    info = "La raiz cuadrada es: " + str(self.res)
    return info

  #CODIGO PRONCIPAL
  #CREAR OBJ

obj_raiz = Raiz()
dato_l = obj_raiz.tomar_l()
obj_raiz.asignar_datos(dato_l)
obj_raiz.calcular()
print(obj_raiz.imprimir())

#EJERCICIO #28
#algoritmo que solicite la base y la altura de un triángulo y
#calcule su área

class Triangulo:
  def __init__(self):
    self.altura = " "
    self.base = " "
    self.resultado = " "

  def tomar_base(self):
    base = int(input("Digite la base: "))
    return base

  def tomar_altura(self):
    altura = int(input("Digite la altura: "))
    return altura
#SETTEAR

  def asignar_datos(self, altura, base):
    self.altura = altura
    self.base = base

  def calcular_area(self):
    self.resultado = (self.base * self.altura)/2

  def imprimir(self):
    info ="El resultado es: " + str(self.resultado)
    return info

obj_triangulo = Triangulo()
dato_altura = obj_triangulo.tomar_altura()
dato_base = obj_triangulo.tomar_base()
obj_triangulo.asignar_datos(dato_altura, dato_base)
obj_triangulo.calcular_area()
print(obj_triangulo.imprimir())

#EJERCICIO #29
#programa que pida un número y determine si es par o impar
#usando el operador de módulo (%)

class Par():
  def __init__(self):
    self.n1 = " "
    self.res = " "

  def tomar_n1(self):
    n1 = int(input("Digite el numero: "))
    return n1

#SETTEAR

  def asignar_datos(self, n1):
    self.n1 = n1

  def calcular(self):
    self.res = (self.n1 % 2)

  def imprimir(self):
    if self.n1 % 2 == 0:
      info = "El numero " + str(self.n1) + " Es Par"

    else:
      info = "El numero " + str(self.n1) + " Es Impar"
    return info

#CREACION DE OBJ
obj_par = Par()
dato_n1 = obj_par.tomar_n1()
obj_par.asignar_datos(dato_n1)
obj_par.calcular()
print(obj_par.imprimir())

#EJERCICIO #30
#algoritmo que solicite el radio de un círculo y calcule su
#circunferencia

class Circulo:
  def __init__(self):
    self.r = " "
    self.res = " "

  def tomar_r(self):
    r = float(input("DIgite el radio del circulo: "))
    return r

  #SETTEAT

  def asignar_datos(self, r ):
    self.r = r

  def calcular(self):
    self.res = (2 * 3.14 * self.r)

  def imprimir(self):
    info = "La circunferencia del circulo es: " + str(self.res)
    return info

  #CREAMOS OBJ

obj_circulo= Circulo()
dato_r= obj_circulo.tomar_r()
obj_circulo.asignar_datos(dato_r)
obj_circulo.calcular()
print(obj_circulo.imprimir())

#EJERCICIO #31
#programa que pida un número de horas y lo convierta a
#minutos utilizando operadores aritméticos

class Min:
  def __init__(self):
    self.h = " "
    self.res = " "

  def tomar_h(self):
    h = float(input("DIgite las litros: "))
    return h

  #SETTEAR

  def asignar_datos(self, h):
    self.h = h

  def calcular(self):
    self.res = (self.h * 60)

  def imprimir(self):
    info = "Las horas a min dan: " + str(self.res)
    return info

  #CODIGO PRONCIPAL
  #CREAR OBJ

obj_min = Min()
dato_h = obj_min.tomar_h()
obj_min.asignar_datos(dato_h)
obj_min.calcular()
print(obj_min.imprimir())

#EJERCICIO #32
#Calcular el area de un rectangulo con la longitud y ancho
class Rectangulo:
  def __init__(self):
    self.longitud= " "
    self.ancho= " "
    self.res = " "

  def tomar_longitud(self):
    longitud = float(input("Digite la longitud del rectangulo: "))
    return longitud

  def tomar_ancho(self):
    ancho = float(input("Digite el ancho del rectangulo: "))
    return ancho

  #SETTEAR

  def asignar_datos(self, longitud, ancho):
    self.longitud = longitud
    self.ancho = ancho

  def calcular_area(self):
    self.res = (self.longitud*self.ancho)

  def imprimir(self):
    info = "El resultado es: " + str(self.res)
    return info

  #LLAMR O CREAR EL OBJETO

obj_rectangulo = Rectangulo()
dato_longitud = obj_rectangulo.tomar_longitud()
dato_ancho = obj_rectangulo.tomar_ancho()

obj_rectangulo.asignar_datos(dato_longitud, dato_ancho)
obj_rectangulo.calcular_area()
print(obj_rectangulo.imprimir())

#EJERCICIO #33
# algoritmo que solicite una distancia en kilómetros y la convierta
#a millas

class Mil:
  def __init__(self):
    self.k = 0
    self.res = 0

  def tomar_k(self):
    k = float(input("DIgite las litros: "))
    return k

  #SETTEAR

  def asignar_datos(self, k):
    self.k = k

  def calcular(self):
    self.res = (self.k * 0.621371)

  def imprimir(self):
    info = "Los kilometros a millas dan: " + str(self.res)
    return info

  #CODIGO PRONCIPAL
  #CREAR OBJ

obj_mil = Mil()
dato_k = obj_mil.tomar_k()
obj_mil.asignar_datos(dato_k)
obj_mil.calcular()
print(obj_mil.imprimir())

#EJERCICIO #34
#programa que pida el precio de un artículo y calcule el 10%
#de descuento

class Des:
  def __init__(self):
    self.p = 0
    self.res = 0

  def tomar_p(self):
    p = float(input("DIgite el precio del articulo: "))
    return p

  #SETTEAR

  def asignar_datos(self, p):
    self.p = p

  def calcular(self):
    self.res = (self.p * 0.10)
    self.res = (self.p -10)

  def imprimir(self):
    info = "El articulo con el descuento queda en: " + str(self.res)
    return info

  #CODIGO PRONCIPAL
  #CREAR OBJ

obj_des = Des()
dato_p = obj_des.tomar_p()
obj_des.asignar_datos(dato_p)
obj_des.calcular()
print(obj_des.imprimir())

#EJERCICIO #35
#algoritmo que solicite la cantidad de dinero en una cuenta y
#calcule el 5% de interés.

class Des:
  def __init__(self):
    self.c = 0
    self.res = 0

  def tomar_c(self):
    c = float(input("DIgite el precio del articulo: "))
    return c

  #SETTEAR

  def asignar_datos(self, c):
    self.c = c

  def calcular(self):
    self.res = (self.c * 0.05)

  def imprimir(self):
    info = "El articulo con el descuento queda en: " + str(self.res)
    return info

  #CODIGO PRONCIPAL
  #CREAR OBJ

obj_des = Des()
dato_c = obj_des.tomar_c()
obj_des.asignar_datos(dato_c)
obj_des.calcular()
print(obj_des.imprimir())

#EJERCICIO #36
#programa que pida dos números enteros y muestre el
#cociente de la división entera

class Div:
  def __init__(self):
    self.n1 = 0
    self.n2 = 0
    self.res = 0

  def tomar_n1(self):
    n1 = int(input("Digite el numero 1: "))
    return n1

  def tomar_n2(self):
    n2 = int(input("Digite el numero 2: "))
    return n2

  #SETEAR

  def asignar_datos(self, n1, n2):
    self.n1 = n1
    self.n2 = n2

  def calcular(self):
    self.res = (self.n1 // self.n2)

  def imprimir(self):
    info = "El cociente es : " + str(self.res)
    return info

  #CODIGO PRINCIPAL
  #CREACION DE OBJETOS

obj_div = Div()
dato_n1 = obj_div.tomar_n1()
dato_n2 = obj_div.tomar_n2()
obj_div.asignar_datos(dato_n1, dato_n2)
obj_div.calcular()
print(obj_div.imprimir())

#EJERCICIO #37
#algoritmo que determine si un número es múltiplo de otro
#ingresados por el usuario

class Mul:
  def __init__(self):
    self.n1 = 0
    self.n2 = 0
    self.res = 0

  def tomar_n1(self):
    n1 = int(input("Digite el n1: "))
    return n1

  def tomar_n2(self):
    n2 = int(input("Digite el n2: "))
    return n2

#SETTEAR

  def asignar_datos(self, n1, n2):
    self.n1 = n1
    self.n2 = n2

  def calcular(self):
    self.res = (self.n1 % self.n2)

  def imprimir(self):
    if self.n1 % self.n2 == 0:
      info = "El numero n1: " + str(self.n1) + " Si es multiplo de n2: " + str(self.n2)
    else:
      info = "El numero n1: " + str(self.n1) + " NO es multiplo de n2: " + str(self.n2)
    return info

#CREARMOS OBJ

obj_mul = Mul()
dato_n1 = obj_mul.tomar_n1()
dato_n2 = obj_mul.tomar_n2()
obj_mul.asignar_datos(dato_n1, dato_n2)
obj_mul.calcular()
print(obj_mul.imprimir())

#EJERCICIO #38
#programa que pida dos números y muestre el mayor de
#Los dos utilizando operadores aritméticos

class May:
  def __init__(self):
    self.n1 = 0
    self.n2 = 0

  def tomar_n1(self):
    self.n1 = int(input("Digite el n1: "))

  def tomar_n2(self):
    self.n2 = int(input("Digite el n2: "))

#SETTEAR

  def calcular(self):
    self.res = (self.n1 > self.n2)

  def imprimir(self):
    if self.n1 > self.n2:
      info = "El n1: " + str(self.n1) + " Es Mayor"
    else:
      info = "El n2: " + str(self.n2) + " Es Mayor"
    return info

#CREAMOS OBJ

obj_may = May()
obj_may.tomar_n1()
obj_may.tomar_n2()
obj_may.calcular()
print(obj_may.imprimir())

#EJERCICIO #39
#lgoritmo que solicite dos números y calcule el promedio de ambos

class Prom:
  def __init__(self):
    self.n1 = 0
    self.n2 = 0
    self.res = 0

  def tomar_n1(self):
    self.n1 = int(input("Digite el numero 1: "))

  def tomar_n2(self):
    self.n2 = int(input("Digite el numero 2: "))

  #SETEAR

  def calcular(self):
    self.res = (self.n1+ self.n2)/2

  def imprimir(self):
    info = "El Prom es: " + str(self.res)
    return info

 #CREACION DE OBJETOS

obj_prom = Prom()
obj_prom.tomar_n1()
obj_prom.tomar_n2()
obj_prom.calcular()
print(obj_prom.imprimir())