# -*- coding: utf-8 -*-
"""3. PROGRAMACION POO CON FOR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w-JccPr5Rhk-0E9aPUNHJdOc_ZPYhHKz
"""

"""
#TOMAR METODOS QUE ESTAN EN EL PDF Y USARLOS PARA HACER UN CRUD,
#DEBEN HACER UNA BASE DE DATOS ESTRUCTURADA CON ARRAY,
#DENTRO DEL ARRAY DEBEN TENER LA INFORMACION DEL CLIENTE (SOLO EL NOMBRE).

EN EL CODIGO PRINCIPAL DEBE HACER UN MENU DE TRABAJO COMO INTERFAZ DE USARIO
CON LAS 9 OPCIONES QUE TIENE EL PDF:
1. GUARDAR UN CLIENTE
2. GUARDAR VARIOS CLIENTES
3. INSERTAR CLIENTE EN POSICION DETERMINADA
4. ELIMINAR CLIENTE
5. BUSCAR CLIENTE Y ELIMINAR EL CLIENTE
6. BUSCAR CLIENTE E IMPRIMIR EL CLIENTE
7. BUSCAR CLIENTE
8. CONTAR LAS VECES QUE SE REPITE EL CLIENTE
9. ORDENAR LISTA DE MENOR A MAYOR
10. ORDENAR LISTA DE MAYOR A MENOR
11. VER LA BASE DE DATOS
12. SALIR DEL SISTEMA....

"""

#ZONA DE CLASES

class Lista_cliente:
  #CREAR UN CONSTRUCTOR = CONTRUIR EL OBJETO CON CARACTERISTICAS INICIALES
  def __init__(self):
    #CREO LOS ATRIBUTOS
    self.base_datos = ["maria", "juan"]
    print("la base de datos se creo en blanco")

    #CREO LOS METODOS CON LAS RESPONSABILIDADES
  def guardar_info(self, nombre_cliente):
    self.base_datos.append(nombre_cliente)

  def imprimir(self):
    print(type(self.base_datos))
    print(self.base_datos)
    #MOSTRAR SOLO LA INFORMACION DEL ARRAY
    #PRIMER FOR (INDEX)

    for i in range(len(self.base_datos)):
      print(f"nombre del cliente es: {self.base_datos[i]} ")

    #SEGUNDO FOR (OBJ INTERNOS)
    for nombre_cliente in self.base_datos:
      print(f"nombre del cliente es: {nombre_cliente}")

#ZONA DE CODIGO PRINCIPAL

obj_db = Lista_cliente()
info_cliente = input("Escriba el nombre: ")
obj_db.guardar_info(info_cliente)
obj_db.imprimir()

#EJERCICIO ESTRUCTURAR BASE DE DATOS CON LISTAS
#MENU GUARDAR CLIENTES
#ZONA DE CLASES

class Lista_cliente:

    def __init__(self):
        self.base_datos = []

    def guardar_datos(self):

        while True:

            print("\n----- MENU -----")
            print("\n1. GUARDAR CLIENTE")
            print("2. GUARDAR VARIOS CLIENTES")
            print("3. INSERTAR CLIENTE EN POSICION DETERMINADA")
            print("4. ELIMINAR CLIENTE")
            print("5. BUSCAR CLIENTE Y ELIMINAR")
            print("6. BUSCAR CLIENTE E IMPRIMIR")
            print("7. BUSCAR CLIENTE")
            print("8. CONTAR CUANTAS VECES SE REPITE")
            print("9. ORDENAR DE MENOR A MAYOR")
            print("10. ORDENAR DE MAYOR A MENOR")
            print("11. VER BASE DE DATOS")
            print("12. SALIR")

            op = int(input("\nDigite una opcion: "))

            match op:

                case 1:
                    nombre = input("Digite el nombre del cliente: ")
                    self.base_datos.append(nombre)

                case 2:
                    cantidad = int(input("Cuantos clientes desea guardar?: "))
                    lista_temp = []
                    for i in range(cantidad):
                        nombre = input("Digite el nombre del cliente: ")
                        lista_temp.append(nombre)
                    self.base_datos.extend(lista_temp)

                case 3:
                    nombre = input("Digite el nombre del cliente: ")
                    posicion = int(input("Digite la posicion: "))
                    self.base_datos.insert(posicion, nombre)

                case 4:
                    nombre = input("Digite el cliente a eliminar: ")
                    if nombre in self.base_datos:
                        self.base_datos.remove(nombre)
                        print("Cliente eliminado")
                    else:
                        print("Cliente no encontrado")

                case 5:
                    nombre = input("Digite el cliente a buscar: ")
                    if nombre in self.base_datos:
                        self.base_datos.remove(nombre)
                        print("Cliente eliminado")
                    else:
                        print("Cliente no existe")

                case 6:
                    nombre = input("Digite el cliente a buscar: ")
                    if nombre in self.base_datos:
                        print("Cliente encontrado:", nombre)
                    else:
                        print("Cliente no existe")

                case 7:
                    nombre = input("Digite el cliente a buscar: ")
                    if nombre in self.base_datos:
                        print("Cliente encontrado")
                    else:
                        print("Cliente no encontrado")

                case 8:
                    nombre = input("Digite el cliente: ")
                    cantidad = self.base_datos.count(nombre)
                    print("Se repite:", cantidad, "veces")

                case 9:
                    self.base_datos.sort()
                    print("Lista ordenada")

                case 10:
                    self.base_datos.sort(reverse=True)
                    print("Lista ordenada")

                case 11:
                    print(self.base_datos)

                case 12:
                    print("Saliendo del sistema...")
                    break

# CODIGO PRINCIPAL

obj_db = Lista_cliente()
obj_db.guardar_datos()