# -*- coding: utf-8 -*-
"""4. PROGRAMACION POO CON TUPLAS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bKUWtOW0rta9bnXmURNa1GYXzhFeRNE8

#CONCEPTOS DE TUPLAS

#1. Como se estructura una tupla?

Una Tupla es una estructura que permite guardar diferentes tipos de datos en
una variable, pero esta es inmutable (Significa que no podemos modificar los datos almacenados en esa variable)


La estructura general se crea con parentesis () y se separan con comas cada dato (,)

EJEMPLO:

tupla = (elemento1, elemento2, elemento3)

EJEMPLO:

clientes = ("Juan", "Ana", "Carlos")

En esta tupla:

"Juan" está en la posición = 0

"Ana" está en la posición = 1

"Carlos" está en la posición = 2

También pueden contener diferentes tipos de datos:

datos = ("Juan", 22, "Colombia")

# 2. Como se procede a modificar la informacion dentro de la tupla?

Las Tuplas como tal no pueden modificar la informacion que tienen por dentro, ya que esta es inmutable, ya cuando se crea la tupla no se pueden modificar los datos que ingresaste.

Pero hay una forma con la que se puede hacer de forma indirecta, y es convirtiendola a una Lista en donde se usara asi:

1. Convertir la Tupla a una Lista:
   
   Clientes = (juan, pedro, maria)
   Lista = list(Clientes)

2. Modificar la Lista:

   Lista[1] = "pedro"

3. Volver a Convertir a Tupla:

   Clientes = tuple(Lista)

   Y da como resultado:

    Clientes = "pedro", "juan", "maria"

# 3. Cual es la ventaja de usar una tupla y cual es su funcion?

  Las Ventajas que ofrece una Tupla son las siguientes:

  1. Hacer el codigo mas rapido y eficaz (Cuando no se requiere cambiar los datos)

  2. Son inmutables (Los datos estan mas seguras ya que no se pueden borrar accidentalmente)

  3. Menor Uso de Memoria (Ya que al no tener que modificar la informacion dentro de la tupla, quedara menos codigo por lo tanto se usara menos memoria)

# La Funcion de la Tupla

   Es crear una variable en donde se puedan ingresar diversos tipos de datos, pero se mantienen constantes en todo el codigo, ya que no se pueden modificar mas adelante, lo cual esto hace que el codigo sea mas seguro (ya que no tendremos la inseguridad de eliminar un dato por accidente)
"""

#EJERCICIO TUPLAS
#CONCEPTOS DE TUPLAS

# 4. Realizar ejercicio tienda para la venta de triangulos donde se requiere:

"""
1. tener una clase triangulo
2. tener un contructor que inicialice la info del triangulo
3. que la info se almacene en la siguiente estructura
db_info = [ ( lado , altura , área ) , ( lado , altura , área ) ]

4. incluir menu de ventas y almacenamiento de datos
(crear, modificar, guardar y buscar)

"""

class Triangulo:
  def __init__(self):
    self.db_info = []

  def calcular(self, lado, altura):
    return (lado*altura) /2

  def menu(self):

    while True:

      print("\n -------------MENU DE TRIANGULOS---------------")
      print(" 1. Crear Triangulo")
      print(" 2. Modificar Triangulo")
      print(" 3. Guardar y Buscar Triangulo")
      print(" 4. Ver la Base de Datos")
      print(" 5. Salir del Sistema...")

      op = int(input("\nDigite una Opcion del (1 - 5)"))

      match op:

        case 1:
          lado = float(input("\nDigite el lado: "))
          altura = float(input("Digite la altura: "))
          area = self.calcular(lado, altura)

          triangulo = (lado, altura, area)
          self.db_info.append(triangulo)
          print("Triangulo Guardado")

        case 2:
          pos = int(input("Digite la posicion del Triangulo a modificar: "))

          if pos < len(self.db_info):
            lado = float(input("Digite el nuevo lado: "))
            altura = float(input("Digite la nueva altura: "))

            area = self.calcular(lado, altura)
            nuevo_triangulo = (lado, altura, area)

            self.db_info[pos] = nuevo_triangulo
            print("Triangulo modificado exitosamente.")
          else:
            print("Posicion fuera de rango. No se pudo modificar el triangulo.")

        case 3:
          pos = int(input("Digite la posicion a buscar: "))

          if pos < len(self.db_info):

            selected_triangulo = self.db_info[pos]

            print("Lado:", selected_triangulo[0])
            print("Altura:", selected_triangulo[1])
            print("Area:", selected_triangulo[2])

          else:
            print("Triangulo no encontrado")

        case 4:
          print("\nBASE DE DATOS: ")
          print(self.db_info)

        case 5:
          print("Saliendo del sistema...")
          break

#ZONA DE CODIGO PRNCIPAL
#CREAMOS OBJ

obj_db = Triangulo()
obj_db.menu()