# -*- coding: utf-8 -*-
"""5. CLASES PADRE E HIJA PYTHON

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kU9NoUQO0Bd9tLMKIRRrnSrTjyKSA4DW
"""

# CLASE PADRE
class Botella:

    def __init__(self, capacidad, material):
        self._capacidad = capacidad
        self._material = material

    # GETTERS
    def get_capacidad(self):
        return self._capacidad

    def get_material(self):
        return self._material

    # SETTERS
    def set_capacidad(self, nuevo_datoc):
        self._capacidad = nuevo_datoc

    def set_material(self, nuevo_datom):
        self._material = nuevo_datom

    def crear_botella(self):
      info = (f"Botella Creada")
      return info

    def ver_info(self):
      print(f"la capacidad es: {self._capacidad}")
      print(f"material es: {self._material}")


# CLASE HIJA 1
class Vidrio(Botella):
    def __init__(self, capacidad, material, color):
        super().__init__(capacidad, material)
        self._color = color

    def get_color(self):
        return self._color

    def set_color(self, nuevo_datocolor):
        self._color = nuevo_datocolor

#POLISMORFISMO

    def ver_info(self):
        super().ver_info()
        print(f"Color: {self._color}")

#CLASE HIJA 2
class Plastico(Botella):
  def __init__(self, capacidad, material, tipo_tapa):
        super().__init__(capacidad, material)
        self._tipo_tapa = tipo_tapa

  def get_tipo_tapa(self):
    return self._tipo_tapa

  def set_tipo_tapa(self, nuevo_datot):
        self._tipo_tapa = nuevo_datot

  #POLIMORFISMO
  def ver_info(self):
        super().ver_info()
        print(f"Tipo de Tapa: {self._tipo_tapa}")

# CODIGO PRINCIPAL
botella = Botella("1 L", "plastico")
print("-----------DATOS_BOTELLA-------------")
botella.ver_info()

vidrio = Vidrio("2 L", "vidrio", "gris")
print("\n-----------DATOS_BOTELLA_VIDRIO--------")
vidrio.ver_info()

plastico = Plastico("1 L", "plastico", "plastica")
print("\n-----------DATOS_BOTELLA_PLASTICO--------")
plastico.ver_info()

# CLASE PADRE
class Carro:

    def __init__(self, marca, modelo):
        self._marca = marca
        self._modelo = modelo

    # GETTERS

    def get_marca(self):
        return self._marca

    def get_modelo(self):
        return self._modelo

    # SETTERS
    def set_marca(self, nueva_marca):
        self._marca = nueva_marca

    def set_modelo(self, nuevo_modelo):
        self._modelo = nuevo_modelo

    def crear_carro(self):
        return "Carro creado correctamente"

    def ver_info(self):
        print(f"Marca: {self._marca}")
        print(f"Modelo: {self._modelo}")


# CLASE HIJA 1
class Deportivo(Carro):
    def __init__(self, marca, modelo, velocidad_max):
        super().__init__(marca, modelo)
        self._velocidad_max = velocidad_max

    def get_velocidad_max(self):
        return self._velocidad_max

    def set_velocidad_max(self, nueva_velocidad):
        self._velocidad_max = nueva_velocidad

    #POLIMORFISMO
    def ver_info(self):
        super().ver_info()
        print(f"Velocidad máxima: {self._velocidad_max}")


# CLASE HIJA 2
class Camion(Carro):
    def __init__(self, marca, modelo, capacidad_carga):
        super().__init__(marca, modelo)
        self._capacidad_carga = capacidad_carga

    def get_capacidad_carga(self):
        return self._capacidad_carga

    def set_capacidad_carga(self, nueva_capacidad):
        self._capacidad_carga = nueva_capacidad

    # POLIMORFISMO
    def ver_info(self):
        super().ver_info()
        print(f"Capacidad de carga: {self._capacidad_carga}")


# CLASE HIJA 3
class Buseta(Carro):
    def __init__(self, marca, modelo, pasajeros):
        super().__init__(marca, modelo)
        self._pasajeros = pasajeros

    def get_pasajeros(self):
        return self._pasajeros

    def set_pasajeros(self, nuevos_pasajeros):
        self._pasajeros = nuevos_pasajeros

    # POLIMORFISMO
    def ver_info(self):
        super().ver_info()
        print(f"Cantidad de pasajeros: {self._pasajeros}")


# CODIGO PRINCIPAL
carro = Carro("Toyota", "2025")
print("-----------DATOS_CARRO-------------")
carro.ver_info()

deportivo = Deportivo("Ferrari", "F8", "340 km/h")
print("\n-----------DATOS_DEPORTIVO-------------")
deportivo.ver_info()

camion = Camion("Volvo", "FH", "20 toneladas")
print("\n-----------DATOS_CAMION-------------")
camion.ver_info()

buseta = Buseta("Mercedes-Benz", "Sprinter", 15)
print("\n-----------DATOS_BUSETA-------------")
buseta.ver_info()

# CLASE PADRE
class Animal:

    def __init__(self, nombre, tipo):
        self._nombre = nombre
        self._tipo = tipo

    # GETTERS
    def get_nombre(self):
        return self._nombre

    def get_tipo(self):
        return self._tipo

    # SETTERS
    def set_nombre(self, nuevo_nombre):
        self._nombre = nuevo_nombre

    def set_tipo(self, nuevo_tipo):
        self._tipo = nuevo_tipo

    def crear_animal(self):
        return "Animal creado correctamente"

    def ver_info(self):
        print(f"Nombre: {self._nombre}")
        print(f"Tipo: {self._tipo}")


# CLASE HIJA 1
class Caballo(Animal):
    def __init__(self, nombre, tipo, velocidad):
        super().__init__(nombre, tipo)
        self._velocidad = velocidad

    def get_velocidad(self):
        return self._velocidad

    def set_velocidad(self, nueva_velocidad):
        self._velocidad = nueva_velocidad

    # POLIMORFISMO
    def ver_info(self):
        super().ver_info()
        print(f"Velocidad: {self._velocidad}")


# CLASE HIJA 2
class Cocodrilo(Animal):
    def __init__(self, nombre, tipo, habitat):
        super().__init__(nombre, tipo)
        self._habitat = habitat

    def get_habitat(self):
        return self._habitat

    def set_habitat(self, nuevo_habitat):
        self._habitat = nuevo_habitat

    # POLIMORFISMO
    def ver_info(self):
        super().ver_info()
        print(f"Hábitat: {self._habitat}")


# CLASE HIJA 3
class Pez(Animal):
    def __init__(self, nombre, tipo, tipo_agua):
        super().__init__(nombre, tipo)
        self._tipo_agua = tipo_agua

    def get_tipo_agua(self):
        return self._tipo_agua

    def set_tipo_agua(self, nuevo_tipo_agua):
        self._tipo_agua = nuevo_tipo_agua

    # POLIMORFISMO
    def ver_info(self):
        super().ver_info()
        print(f"Tipo de agua: {self._tipo_agua}")


# CLASE HIJA 4
class Escarabajo(Animal):
    def __init__(self, nombre, tipo, color):
        super().__init__(nombre, tipo)
        self._color = color

    def get_color(self):
        return self._color

    def set_color(self, nuevo_color):
        self._color = nuevo_color

    # POLIMORFISMO
    def ver_info(self):
        super().ver_info()
        print(f"Color: {self._color}")


# CLASE HIJA 5
class Pato(Animal):
    def __init__(self, nombre, tipo, puede_volar):
        super().__init__(nombre, tipo)
        self._puede_volar = puede_volar

    def get_puede_volar(self):
        return self._puede_volar

    def set_puede_volar(self, nuevo_valor):
        self._puede_volar = nuevo_valor

    # POLIMORFISMO
    def ver_info(self):
        super().ver_info()
        print(f"Puede volar?: {self._puede_volar}")


# CODIGO PRINCIPAL
animal = Animal("Gato", "Terrestre")
print("-----------DATOS_ANIMAL-------------")
animal.ver_info()

caballo = Caballo("Spirit", "Terrestre", "88 km/h")
print("\n-----------DATOS_CABALLO-------------")
caballo.ver_info()

cocodrilo = Cocodrilo("Coco", "Reptil", "Ríos y pantanos")
print("\n-----------DATOS_COCODRILO-------------")
cocodrilo.ver_info()

pez = Pez("Nemo", "Acuático", "Agua salada")
print("\n-----------DATOS_PEZ-------------")
pez.ver_info()

escarabajo = Escarabajo("Escara", "Insecto", "Negro")
print("\n-----------DATOS_ESCARABAJO-------------")
escarabajo.ver_info()

pato = Pato("Donald", "Ave", "Si, un poco")
print("\n-----------DATOS_PATO-------------")
pato.ver_info()

class Juego:
  def __init__(self, nombre, tipo):
    self._nombre = nombre
    self._tipo = tipo

  def get_nombre(self):
    return self._nombre

  def get_tipo(self):
    return self._tipo

  def set_nombre(self, nuevo_nombre):
    self._nombre = nuevo_nombre

  def set_tipo(self, nuevo_tipo):
    self._tipo = nuevo_tipo

  def crear_juego(self):
    return "Juego creado correctamente"

  def ver_info(self):
    print(f"El nombre es: {self._nombre}")
    print(f"El tipo es: {self._tipo}")

class Game1(Juego):
  def __init__(self, nombre, tipo, multijugador):
    super().__init__(nombre, tipo)
    self._multijugador = multijugador

  def get_multijugador(self):
    return self._multijugador

  def set_multijugador(self, nuevo_valor):
    self._multijugador = nuevo_valor

  def ver_info(self):
      super().ver_info()
      print(f"Es Multijugador el Juego?: {self._multijugador}")

class Game2(Juego):
  def __init__(self, nombre, tipo, chat_voz):
    super().__init__(nombre, tipo)
    self._chat_voz = chat_voz

  def get_chat_voz(self):
    return self._chat_voz

  def set_chat_voz(self, nueva_op):
    self._chat_voz = nueva_op

  def ver_info(self):
    super().ver_info()
    print(f"Tiene Chat de Voz?: {self._chat_voz}")

class Game3(Juego):
  def __init__(self, nombre, tipo, tryhard):
      super().__init__(nombre, tipo)
      self._tryhard = tryhard

  def get_tryhard(self):
    return self._tryhard

  def set_tryhard(self, nuevo_v):
    self._tryhard = nuevo_v

  def ver_info(self):
      super().ver_info()
      print(f"El Juego es Tryhard?: {self._tryhard}")

#CODIGO PRINCIPAL

game = Juego("Fornite", "disparos")
print("------------INFO GAME------------")
game.ver_info()

game1 = Game1("Minecraft", "Aventuras", " Si")
print("\n----------INFO GAME 1----------")
game1.ver_info()

game2 = Game2("Clash Royale", "Tacticas", " no")
print("\n----------INFO GAME 2----------")
game2.ver_info()

game3 = Game3("Blood Strike", "disparos", "Si, hay demasiados Tryhards")
print("\n----------INFO GAME 3----------")
game3.ver_info()