# -*- coding: utf-8 -*-
"""Ejemplo clases

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZzI1lAEoX8eZQ_5rZG4cIqFPV0EcHCc
"""

class Usuario:
  def __init__(self, nombre, tipo):
    self.nombre = nombre
    self.tipo = tipo

  def get_nombre(self):
    return self.nombre

  def get_tipo(self):
    return self.tipo

  def set_nombre(self, nuevo_nombre):
    self.nombre = nuevo_nombre

  def set_tipo(self, nuevo_tipo):
    self.tipo = nuevo_tipo

  def ver_info(self):
    print(f"El nombre del usuario es: {self.nombre}")
    print(f"El Tipo del usuario es: {self.tipo}")

class Saludo:
  def __init__(self):
    self.saludo = "Hola Usuario: "

  def crear_saludo(self, objusuario):
    saludo = self.saludo + objusuario.get_nombre() + objusuario.get_tipo()
    return saludo

#CODIGO PRINCIPAL
usuariosaludo = Usuario("pablo, ", "Admin")
saludador = Saludo()
mensaje = saludador.crear_saludo(usuariosaludo)
print(mensaje)